pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenLocal()
        // NOTE (fork fix): mccheatz.github.io/maven_repo is dead (org deleted),
        // mirror of the same repo content hosted for ProtoHax builds.
        maven { url = 'https://raw.githubusercontent.com/SkidderMC/ProtoHax-PackageGit/main/maven_repo/' }
        google()
        mavenCentral()
    }
}
rootProject.name = 'ProtoHax-Android'
include ':app'

